accounts/urls.py
from django.urls import path
from accounts.views import *
app_name = 'accounts'

urlpatterns = [
    path('register/', RegisterView.as_view(), name='register'),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('dashboard', DashboardView.as_view(), name='dashboard'),

    path('forgot-password/', ForgotPasswordView.as_view(), name='forgot-password'),
    path('resetpassword_validate/<uidb64>/<token>/', ResetPasswordValidateView.as_view(), name='resetpassword_validate'),
    path('reset-password/', ResetPasswordView.as_view(), name='reset-password'),
    path('activate/<uidb64>/<token>/', ActivateAccountView.as_view(), name='activate'),

    path('my_orders/',MyOrdersView.as_view(), name='my_orders'),
    path('edit_profile/', EditProfileView.as_view(), name='edit_profile'),
    path('change_password/', ChangePasswordView.as_view(), name='change_password'),
    path('order_detail/<int:order_id>/', OrderDetailView.as_view(), name='order_detail'),
]

api/urls.py
from django.urls import path, include
from api.views import *
from rest_framework.routers import DefaultRouter

router = DefaultRouter()
router.register(r'add-to-cart', AddToCartView, basename='add-to-cart')

app_name = 'api'
urlpatterns=[
    ############### Store ###########
    path('', StoreView.as_view(), name='store'),
    path('category/<slug:category_slug>/', StoreView.as_view(), name='products_by_category'),
    path('category/<slug:category_slug>/<slug:product_slug>/', ProductDetailView.as_view(), name='product_detail'),
    path('search/', SearchView.as_view(), name='search'),

    ############### Carts ###########
    path('cart/', CartView.as_view(), name='cart'),
    # path('add-to-cart/<int:product_id>/', AddToCartView.as_view(), name='add-to-cart'),
    path('remove-cart/<int:product_id>/<int:cart_item_id>/', RemoveCartView.as_view(), name='remove-cart'),
    path('delete-cart/<int:product_id>/<int:cart_item_id>/', RemoveCartItemView.as_view(), name='delete-cart'),
    path('checkout/', CheckoutView.as_view(), name='checkout'),

    path('', include(router.urls)),

    path('payments/', Payments.as_view(), name='payments'),
    path('place-order/', PlaceOrder.as_view(), name='place-order'),
    path('order-complete/', OrderCompleteView.as_view(), name='order-complete'),



    # path('register/', RegisterView.as_view(), name='register'),

]

ecommerce/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from .views import IndexView
from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
)
from drf_spectacular.views import SpectacularAPIView, SpectacularSwaggerView, SpectacularRedocView


urlpatterns = [
    path('admin/', include('admin_honeypot.urls', namespace='admin_honeypot')),
    path("securelogin/", admin.site.urls),
    path('', IndexView.as_view(), name='index'),
    path('category/', include('category.urls', namespace='category')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('store/', include('store.urls', namespace='store')),
    path('cart/', include('carts.urls', namespace='carts')),
    path('api/', include('api.urls', namespace='api')),
    path('order/', include('order.urls', namespace='order')),
    
    # JWT authentication views
    path('api/token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('api/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),

    # Djoser authentication URLs
    path('auth/', include('djoser.urls')),  
    path('auth/', include('djoser.urls.authtoken')),
    
    # SWAGGER with drf_spectacular
    path('api/schema/', SpectacularAPIView.as_view(), name='schema'),
    path('api/swagger/', SpectacularSwaggerView.as_view(url_name='schema'), name='swagger-ui'),
    path('api/redoc/', SpectacularRedocView.as_view(url_name='schema'), name='redoc'),
       
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/includes/alerts.html
{% if messages %}

    {% for message in messages %}
    <div id="message" class="container">
    <div {% if message.tags %} class="alert alert-{{ message.tags }}"{% endif %} role="alert">
      <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span></button>
        {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}Error: {% endif %}
        {{ message }}
    </div>
    </div>
    {% endfor %}

{% endif %}

templates/includes/dashboard_sidebar.html
<aside class="col-md-3">
    <!--   SIDEBAR   -->
    <ul class="list-group">
      <a class="list-group-item {% if '/dashboard' in request.path %}active{% endif %}" href="{% url 'accounts:dashboard' %}"> Dashboard </a>
      <a class="list-group-item {% if '/my_orders/' in request.path %}active{% endif %}" href="{% url 'accounts:my_orders' %}"> My Orders </a>
      <a class="list-group-item {% if '/edit_profile/' in request.path %}active{% endif %}" href="{% url 'accounts:edit_profile' %}"> Edit Profile </a>
      <a class="list-group-item {% if '/change_password/' in request.path %}active{% endif %}" href="{% url 'accounts:change_password' %}"> Change Password </a>
    </ul>
    <br>
    <a class="btn btn-light btn-block" href="{% url 'accounts:logout' %}"> <i class="fa fa-power-off"></i> <span class="text">Log out</span> </a>
    <!--   SIDEBAR .//END   -->
  </aside>

templates/includes/footer.html
{% load static %}

<!-- ========================= FOOTER ========================= -->
<footer class="section-footer border-top">
	<div class="container">
		<section class="footer-bottom border-top row">
			<div class="col-md-2">
				<p class="text-muted"> &copy 2023 Hosseinhtt </p>
			</div>
			<div class="col-md-8 text-md-center">
				<span  class="px-2">hossein.taybi@yahoo.com</span>
				<span  class="px-2">+989306087131</span>
				<span  class="px-2">Tehran, Iran</span>
			</div>
			<div class="col-md-2 text-md-right text-muted">
				<i class="fab fa-lg fa-cc-visa"></i>
				<i class="fab fa-lg fa-cc-paypal"></i>
				<i class="fab fa-lg fa-cc-mastercard"></i>
			</div>
		</section>
	</div><!-- //container -->
</footer>
<!-- ========================= FOOTER END // ========================= -->


<script src="https://code.jquery.com/jquery-3.7.1.js" integrity="sha256-eKhayi8LEQwp4NKxN+CfCh+3qOVUtJn3QNZ0TciWLP4=" crossorigin="anonymous"></script>

<script>
$(document).ready(function(){
	$('.thumb a').click(function(e){
		e.preventDefault();
		$('.mainImage img').attr('src', $(this).attr('href'));
	})
})

</script>

templates/includes/navbar.html
{% load static %}
<header class="section-header">
    <nav class="navbar p-md-0 navbar-expand-sm navbar-light border-bottom">
    <div class="container">
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTop4" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarTop4">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item dropdown">
                 <a href="#" class="nav-link">   English </a>
                
            </li>
            <li class="nav-item dropdown">
                <a href="#" class="nav-link"> USD </a>
            </li>
        </ul>
        <ul class="navbar-nav">
            <li><a href="mailto:hossein.taybi@yahoo.com" class="nav-link"> <i class="fa fa-envelope"></i> Email </a></li>
            <li><a href="tel:+989306087131" class="nav-link"> <i class="fa fa-phone"></i> Call us </a></li>
        </ul><!-- list-inline //  -->
      </div> <!-- navbar-collapse .// -->
    </div> <!-- container //  -->
    </nav>
    
    <section class="header-main border-bottom">
        <div class="container">
    <div class="row align-items-center">
        <div class="col-lg-2 col-md-3 col-6">
            <a href="{% url 'index' %}" class="brand-wrap">
                <img class="logo" src="{% static './images/logo.png' %}">
            </a> <!-- brand-wrap.// -->
        </div>
        <div class="col-lg col-sm col-md col-6 flex-grow-0">
            <div class="category-wrap dropdown d-inline-block float-right">
                <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown"> 
                    <i class="fa fa-bars"></i> All category 
                </button>
                <div class="dropdown-menu">
                    <a class="dropdown-item" href="{% url 'store:store' %}">All Products </a>

                    {% for category in links %}
                    <a class="dropdown-item" href="{% url 'store:products_by_category' category_slug=category.slug %}">{{category.category_name}} </a>
                    {% endfor %}
                </div>
            </div>  <!-- category-wrap.// -->
        </div> <!-- col.// -->
        <a href="{% url 'store:store' %}" class="btn btn-outline-primary">Store</a>
        <div class="col-lg  col-md-6 col-sm-12 col">
            <form action="{% url 'store:search' %}" class="search" method="GET">
                <div class="input-group w-100">
                    <input type="text" class="form-control" style="width:60%;" placeholder="Search" name="keyword">
                    
                    <div class="input-group-append">
                      <button class="btn btn-primary" type="submit">
                        <i class="fa fa-search"></i>
                      </button>
                    </div>
                </div>
            </form> <!-- search-wrap .end// -->
        </div> <!-- col.// -->
        <div class="col-lg-3 col-sm-6 col-8 order-2 order-lg-3">
                    <div class="d-flex justify-content-end mb-3 mb-lg-0">
                        <div class="widget-header">
                            {% if request.user.is_authenticated %}
                            <small class="title text-muted">{{request.user.username}}</small>
                            {% else %}
                            <small class="title text-muted">Welcome Guest!</small>
                            {% endif %}
                            <div>
                                {% if request.user.is_authenticated %}
                                <a href="{% url 'accounts:dashboard' %}">Dashboard</a> <span class="dark-transp"> | </span>
                                <a href="{% url 'accounts:logout' %}">Sign out</a> <span class="dark-transp">  </span>
                                {% else %}
                                <a href="{% url 'accounts:login' %}">Sign in</a> <span class="dark-transp"> | </span>
                                <a href="{% url 'accounts:register' %}"> Register</a>
                                {% endif %}
                            </div>
                        </div>
                        <a href="{% url 'carts:cart' %}" class="widget-header pl-3 ml-3">
                            <div class="icon icon-sm rounded-circle border"><i class="fa fa-shopping-cart"></i></div>
                            <span class="badge badge-pill badge-danger notify">{{cart_count}}</span>
                        </a>
                    </div> <!-- widgets-wrap.// -->
                </div> <!-- col.// -->
    </div> <!-- row.// -->
        </div> <!-- container.// -->
    </section> <!-- header-main .// -->
    
    
    
    
    </header> <!-- section-header.// -->