accounts/urls.py
from django.urls import path
from accounts.views import *
app_name = 'accounts'

urlpatterns = [
    path('register/', RegisterView.as_view(), name='register'),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('dashboard', DashboardView.as_view(), name='dashboard'),

    path('forgot-password/', ForgotPasswordView.as_view(), name='forgot-password'),
    path('resetpassword_validate/<uidb64>/<token>/', ResetPasswordValidateView.as_view(), name='resetpassword_validate'),
    path('reset-password/', ResetPasswordView.as_view(), name='reset-password'),
    path('activate/<uidb64>/<token>/', ActivateAccountView.as_view(), name='activate'),

    path('my_orders/',MyOrdersView.as_view(), name='my_orders'),
    path('edit_profile/', EditProfileView.as_view(), name='edit_profile'),
    path('change_password/', ChangePasswordView.as_view(), name='change_password'),
    path('order_detail/<int:order_id>/', OrderDetailView.as_view(), name='order_detail'),
]

api/urls.py
from django.urls import path, include
from api.views import *
from rest_framework.routers import DefaultRouter

router = DefaultRouter()
router.register(r'add-to-cart', AddToCartView, basename='add-to-cart')

app_name = 'api'
urlpatterns=[
    ############### Store ###########
    path('', StoreView.as_view(), name='store'),
    path('category/<slug:category_slug>/', StoreView.as_view(), name='products_by_category'),
    path('category/<slug:category_slug>/<slug:product_slug>/', ProductDetailView.as_view(), name='product_detail'),
    path('search/', SearchView.as_view(), name='search'),

    ############### Carts ###########
    path('cart/', CartView.as_view(), name='cart'),
    # path('add-to-cart/<int:product_id>/', AddToCartView.as_view(), name='add-to-cart'),
    path('remove-cart/<int:product_id>/<int:cart_item_id>/', RemoveCartView.as_view(), name='remove-cart'),
    path('delete-cart/<int:product_id>/<int:cart_item_id>/', RemoveCartItemView.as_view(), name='delete-cart'),
    path('checkout/', CheckoutView.as_view(), name='checkout'),

    path('', include(router.urls)),

    path('payments/', Payments.as_view(), name='payments'),
    path('place-order/', PlaceOrder.as_view(), name='place-order'),
    path('order-complete/', OrderCompleteView.as_view(), name='order-complete'),



    # path('register/', RegisterView.as_view(), name='register'),

]

carts/urls.py
from django.urls import path
from carts.views import *

app_name = 'carts'

urlpatterns = [
    path('cart/', CartView.as_view(), name='cart'),
    path('add-to-cart/<int:product_id>/', AddToCartView.as_view(), name='add-to-cart'),
    path('remove-cart/<int:product_id>/<int:cart_item_id>/', RemoveCartView.as_view(), name='remove-cart'),
    path('delete-cart/<int:product_id>/<int:cart_item_id>/', RemoveCartItemView.as_view(), name='delete-cart'),

    path('checkout/', CheckoutView.as_view(), name='checkout'),
]

# Define a router for the CartItemViewSet
# from rest_framework.routers import DefaultRouter

# router = DefaultRouter()
# router.register(r'cart-items', CartItemViewSet, basename='cart-item')

# urlpatterns += router.urls

ecommerce/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from .views import IndexView
from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
)
from drf_spectacular.views import SpectacularAPIView, SpectacularSwaggerView, SpectacularRedocView


urlpatterns = [
    path('admin/', include('admin_honeypot.urls', namespace='admin_honeypot')),
    path("securelogin/", admin.site.urls),
    path('', IndexView.as_view(), name='index'),
    path('category/', include('category.urls', namespace='category')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('store/', include('store.urls', namespace='store')),
    path('cart/', include('carts.urls', namespace='carts')),
    path('api/', include('api.urls', namespace='api')),
    path('order/', include('order.urls', namespace='order')),
    
    # JWT authentication views
    path('api/token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('api/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),

    # Djoser authentication URLs
    path('auth/', include('djoser.urls')),  
    path('auth/', include('djoser.urls.authtoken')),
    
    # SWAGGER with drf_spectacular
    path('api/schema/', SpectacularAPIView.as_view(), name='schema'),
    path('api/swagger/', SpectacularSwaggerView.as_view(url_name='schema'), name='swagger-ui'),
    path('api/redoc/', SpectacularRedocView.as_view(url_name='schema'), name='redoc'),
       
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

store/urls.py
from django.urls import path
from store.views import *

app_name = 'store'

urlpatterns = [
    path('', StoreView.as_view(), name='store'),
    path('category/<slug:category_slug>/', StoreView.as_view(), name='products_by_category'),
    path('category/<slug:category_slug>/<slug:product_slug>', ProductDetailView.as_view(), name='product_detail'),
    path('search/', SearchView.as_view(), name='search'),
    path('submit-review/<int:product_id>', SubmitReviewView.as_view(), name='submit-review'),

]

carts/models.py
from django.db import models
from store.models import Product, Variation
from accounts.models import Account


# Create your models here.

class Cart(models.Model):
    cart_id = models.CharField(max_length=250, blank=True)
    date_added = models.DateField(auto_now_add=True)

    def __str__(self):
        return self.cart_id


class CartItem(models.Model):
    user = models.ForeignKey(Account, on_delete=models.CASCADE, null=True)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    variations = models.ManyToManyField(Variation, blank=True)
    cart    = models.ForeignKey(Cart, on_delete=models.CASCADE, null=True)
    quantity = models.IntegerField()
    is_active = models.BooleanField(default=True)

    def sub_total(self):
        return self.product.price * self.quantity

    def __unicode__(self):
        return self.product
    
    def __str__(self):
        return self.product.product_name

store/models.py
from django.db import models
from category.models import Category
from accounts.models import Account
from django.db.models import Avg, Count

# Create your models here.
class Product(models.Model):
    product_name = models.CharField(max_length=200, unique=True)
    slug = models.SlugField(max_length=200, unique=True)
    description = models.TextField(max_length=500, blank=True)
    price = models.IntegerField()
    images = models.ImageField(upload_to='photos/products')
    stock = models.IntegerField()
    is_available = models.BooleanField(default=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    created_date = models.DateTimeField(auto_now_add=True)
    modified_date = models.DateTimeField(auto_now=True)

    def averageReview(self):
        reviews = ReviewRating.objects.filter(product=self, status=True).aggregate(average=Avg('rating'))
        avg = 0
        if reviews['average'] is not None:
            avg = float(reviews['average'])
        return avg
    
    def countReview(self):
        reviews = ReviewRating.objects.filter(product=self, status=True).aggregate(count=Count('id'))
        count = 0
        if reviews['count'] is not None:
            count = int(reviews['count'])
        return count

    def __str__(self):
        return self.product_name
    

class VariationManager(models.Manager):
    def colors(self):
        return super(VariationManager, self).filter(variation_category='color', is_active=True)

    def sizes(self):
        return super(VariationManager, self).filter(variation_category='size', is_active=True)

variation_category_choice = (
    ('color', 'color'),
    ('size', 'size'),
)

class Variation(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    variation_category = models.CharField(max_length=100, choices=variation_category_choice)
    variation_value     = models.CharField(max_length=100)
    is_active           = models.BooleanField(default=True)
    created_date        = models.DateTimeField(auto_now=True)

    objects = VariationManager()

    def __str__(self):
        return self.variation_value    

class ReviewRating(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    user = models.ForeignKey(Account, on_delete=models.CASCADE)
    subject = models.CharField(max_length=100, blank=True)
    review = models.CharField(max_length=500, blank=True)
    rating = models.FloatField()
    ip = models.CharField(max_length=20, blank=True)
    status = models.BooleanField(default=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.subject
    

class ProductGallery(models.Model):
    product = models.ForeignKey(Product, default=None, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='store/products', max_length=255)

    def __str__(self):
        return self.product.product_name

    class Meta:
        verbose_name = 'product gallery'
        verbose_name_plural = 'product gallery'

store/forms.py
from django import forms
from store.models import ReviewRating

class ReviewForm(forms.ModelForm):
    class Meta:
        model = ReviewRating
        fields = ['subject', 'review', 'rating']

store/views.py
from django.shortcuts import render, redirect
from django.views.generic import View, TemplateView, DetailView
from django.shortcuts import get_object_or_404
from django.http import Http404
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.db.models import Q
from django.db import connection
from django.contrib import messages
from django.http import HttpResponseRedirect

from store.models import Product, ReviewRating, ProductGallery
from store.forms import ReviewForm
from category.models import Category
from carts.models import CartItem
from carts.views import CartMixin
from order.models import OrderProduct



class StoreView(TemplateView):
    template_name = 'store/store.html'

    def get_context_data(self, **kwargs):
        category_slug = self.kwargs.get('category_slug')
        
        if category_slug:
            category = get_object_or_404(Category, slug=category_slug)
            products = Product.objects.filter(category=category, is_available=True)
        else:
            products = Product.objects.filter(is_available=True).order_by('-created_date')
        
        paginator = Paginator(products, 3)
        page = self.request.GET.get('page')
        paged_products = paginator.get_page(page)
        product_count = products.count()
        
        context = {
            'products': products,
            'product_count': product_count,
            'paged_products': paged_products
        }

        return context
    

class ProductDetailView(TemplateView):
    template_name = 'store/product_detail.html'

    def get_context_data(self, **kwargs):
        # Get the category_slug and product_slug from URL parameters
        category_slug = self.kwargs.get('category_slug')
        product_slug = self.kwargs.get('product_slug')

        try:
            # Retrieve the product with the given slugs
            product = Product.objects.get(category__slug=category_slug, slug=product_slug, is_available=True)
            
            # Create an instance of CartMixin
            cart_mixin = CartMixin()
            # Use the _cart_id method from CartMixin
            cart_id = cart_mixin._cart_id(self.request)
            
            in_cart = CartItem.objects.filter(cart__cart_id=cart_id, product=product).exists()

        except Product.DoesNotExist:
            # If the product does not exist, raise a 404 error
            raise Http404("Product not found")
        
        if self.request.user.is_authenticated:

            try:
                orderproduct = OrderProduct.objects.filter(user=self.request.user, product_id=product.id).exists()
            except OrderProduct.DoesNotExist:
                orderproduct = None
        else:
            orderproduct = None

        reviews = ReviewRating.objects.filter(product_id=product.id, status=True)

        product_gallery = ProductGallery.objects.filter(product_id=product.id)

        context = {
            'product': product,
            'in_cart': in_cart,
            'reviews': reviews,
            'order_product': orderproduct,
            'product_gallery': product_gallery,

        }
        return context

import logging

logger = logging.getLogger(__name__)

class SearchView(View):
    template_name = 'store/store.html'

    def get(self, request):
        keyword = request.GET.get('keyword', '')

        if keyword:
            products = Product.objects.order_by('-created_date').filter(
                Q(description__icontains=keyword) | Q(product_name__icontains=keyword))
            
            product_count = products.count()
        else:
            products = []
            product_count = 0

        paginator = Paginator(products, 3)
        page = self.request.GET.get('page')
        paged_products = paginator.get_page(page)

        context = {
            'products': products,
            'product_count': product_count,
            'paged_products': paged_products,
        }
        
        return render(request, self.template_name, context)

class SubmitReviewView(View):
    def post(self, request, product_id):
        url = request.META.get('HTTP_REFERER')
        if request.method == 'POST':
            try:
                review = ReviewRating.objects.get(user__id=request.user.id, product__id=product_id)
                form = ReviewForm(request.POST, instance=review)
                form.save()
                messages.success(request, 'Thank you! Your review has been updated.')
                return redirect(url)
            except ReviewRating.DoesNotExist:
                form = ReviewForm(request.POST)
                if form.is_valid():
                    review = form.save(commit=False)  # Create a new review object but don't save it yet
                    review.user = request.user
                    review.product_id = product_id
                    review.ip = request.META.get('REMOTE_ADDR')
                    review.save()  # Save the review now
                    messages.success(request, 'Thank you! Your review has been submitted.')
                    return redirect(url)

templates/store/cart.html
{% extends 'base.html' %}
{% load static %}

{% block content %}


<section class="section-content padding-y bg">
    <div class="container">
    
    <!-- ============================ COMPONENT 1 ================================= -->
    {% if not cart_items %}
    <h2 class="text-center">Your Shopping Cart is Empty</h2>
	<br>
	<div class="text-center">
		<a href="{% url 'store:store' %}" class="btn btn-primary">Continue Shopping</a>
	</div>

    {% else %}
    <div class="row">
        <aside class="col-lg-9">
    <div class="card">
    <table class="table table-borderless table-shopping-cart">
    <thead class="text-muted">
    <tr class="small text-uppercase">
      <th scope="col">Product</th>
      <th scope="col" width="120">Quantity</th>
      <th scope="col" width="120">Price</th>
      <th scope="col" class="text-right" width="200"> </th>
    </tr>
    </thead>
    <tbody>
        {% for item in cart_items %}
        <tr>
            <td>
                <figure class="itemside align-items-center">
                    <div class="aside">
                        <!-- Display the product image -->
                        <img src="{{ item.product.images.url }}" class="img-sm">
                    </div>
                    <figcaption class="info">
                        <!-- Display the product name -->
                        <a href="{% url 'store:product_detail' category_slug=item.product.category.slug product_slug=item.product.slug %}" class="title text-dark">{{ item.product.product_name }}</a>
                        <p class="text-muted small">
                            {% if item.variations.all %}
                                    {% for variation in item.variations.all %}
                                        {{ variation.variation_category|capfirst }}: {{ variation.variation_value|capfirst }}
                                    <br>
                                    {% endfor %}
                                
                            {% endif %}
                        </p>
                    </figcaption>
                </figure>
            </td>
            <td>
                <div class="col">
                    <div class="input-group input-spinner">
                        <div class="input-group-prepend">
                            
                            <form method="GET" action="{% url 'carts:remove-cart' item.product.id item.id%}">
                                {% csrf_token %}
                                <button class="btn btn-light" type="submit" id="button-minus">
                                    <i class="fa fa-minus"></i>
                                </button>
                            </form>
                        </div>
                        <!-- Display the item quantity -->
                        <input type="text" class="form-control" value="{{ item.quantity }}">
                        <div class="input-group-append">
                            <form action="{% url 'carts:add-to-cart' item.product.id %}" method="POST">
                                {% csrf_token %}
                                {% for item in item.variations.all %}
                                    <input type="hidden" name="{{ item.variation_category | lower }}" value="{{ item.variation_value | capfirst }}">
                                {% endfor %}
                                <button class="btn btn-light" type="submit" id="button-minus"> <i class="fa fa-plus"></i> </button>
                            </form>
                        </div>
                    </div> <!-- input-group.// -->
                </div> <!-- col.// -->
            </td>
            <td>
                <div class="price-wrap">
                    <!-- Calculate and display the total price for this item -->
                    <!-- {% with total_price=item.product.price|floatformat:2|default_if_none:0 %} -->
                    <!-- {% with total_quantity=item.quantity %} -->
                    <var class="price">${{ item.sub_total }}</var>
                    <small class="text-muted">
                        <!-- Display the price per item -->
                        ${{item.product.price}} each
                    </small>
                    {% endwith %}
                    {% endwith %}
                </div> <!-- price-wrap .// -->
            </td>
            <td class="text-right">
                <a href="{% url 'carts:delete-cart' item.product.id item.id%}" onclick="return confirm('Are you sure wanna delete this item?')" class="btn btn-danger">
                    Remove
                </a>
            </td>
        </tr>
        {% endfor %}
        
    
    </tbody>
    </table>
    </div> <!-- card.// -->
    
        </aside> <!-- col.// -->
        <aside class="col-lg-3">
    
            <div class="card">
            <div class="card-body">
                <dl class="dlist-align">
                  <dt>Total price:</dt>
                  <dd class="text-right">${{total}}</dd>
                </dl>
                <dl class="dlist-align">
                  <dt>Tax:</dt>
                  <dd class="text-right"> ${{tax}}</dd>
                </dl>
                <dl class="dlist-align">
                  <dt>Total:</dt>
                  <dd class="text-right text-dark b"><strong>${{grand_total}}</strong></dd>
                </dl>
                <hr>
                <p class="text-center mb-3">
                    <img src="{% static './images/misc/payments.png' %}" height="26">
                </p>
                <a href="{% url 'carts:checkout' %}" class="btn btn-primary btn-block"> Checkout </a>
                <a href="{% url 'store:store' %}" class="btn btn-light btn-block">Continue Shopping</a>
            </div> <!-- card-body.// -->
            </div> <!-- card.// -->
    
    </aside> <!-- col.// -->
    
    
    </div> <!-- row.// -->
    <!-- ============================ COMPONENT 1 END .// ================================= -->
    
    </div> <!-- container .//  -->
    {% endif %}
</section>
    <!-- ========================= SECTION CONTENT END// ========================= -->


{% endblock %}

templates/store/product_detail.html
{% extends 'base.html' %}
{% load static %}

{% block content %}


<section class="section-content padding-y bg">
    <div class="container">
    
    <!-- ============================ COMPONENT 1 ================================= -->
    <div class="card">
        <div class="row no-gutters">
            <aside class="col-md-6">
      <article class="gallery-wrap"> 
        <div class="img-big-wrap mainImage">
           <center><img src="{{product.images.url}}"></center>
        </div> <!-- img-big-wrap.// -->
        
      </article> <!-- gallery-wrap .end// -->
      <ul class="thumb">
        <li>
          <a href="{{product.images.url}}" target="mainImage"><img src="{{product.images.url}}" alt="Product Image"></a>

          {% for image in product_gallery%}
          <a href="{{image.image.url}}" target="mainImage"><img src="{{image.image.url}}" alt="Product Image"></a>
          {% endfor %}
        </li>
      </ul>
            </aside>
            <main class="col-md-6 border-left">

    <form action="{% url 'carts:add-to-cart' product.id %}" method="POST">
      {% csrf_token %}

    <article class="content-body">
    
    <h2 class="title">{{product.product_name}}</h2>

    <div class="mb-3"> 
        <var class="price h4">${{product.price}}.00</var> 
    </div> 
    <div class="rating-star">
      <span>
        
        <span>{{product.countReview}} reviews</span>
        <br>
        <i class="fa fa-star{% if product.averageReview < 0.5 %}-o{% elif product.averageReview >= 0.5 and product.averageReview < 1 %}-half-o {% endif %}" aria-hidden="true"></i>
        <i class="fa fa-star{% if product.averageReview < 1.5 %}-o{% elif product.averageReview >= 1.5 and product.averageReview < 2 %}-half-o {% endif %}" aria-hidden="true"></i>
        <i class="fa fa-star{% if product.averageReview < 2.5 %}-o{% elif product.averageReview >= 2.5 and product.averageReview < 3 %}-half-o {% endif %}" aria-hidden="true"></i>
        <i class="fa fa-star{% if product.averageReview < 3.5 %}-o{% elif product.averageReview >= 3.5 and product.averageReview < 4 %}-half-o {% endif %}" aria-hidden="true"></i>
        <i class="fa fa-star{% if product.averageReview < 4.5 %}-o{% elif product.averageReview >= 4.5 and product.averageReview < 5 %}-half-o {% endif %}" aria-hidden="true"></i>
        
      </span>
    </div>
    
    <p>{{product.description}}</p>
    
    
    <hr>
    <div class="row">
      <div class="item-option-select">
        <h6>Choose Color</h6>
        <select name="color" class="form-control" required>
          <option value="" disabled selected>Select</option>
          {% for i in product.variation_set.colors %}
          <option value="{{ i.variation_value | lower }}">{{ i.variation_value | capfirst }}</option>
          {% endfor %}
        </select>
      </div>
    </div>
    <div class="row">
      <div class="item-option-select">
        <h6>Select Size</h6>
        <select name="size" class="form-control">
          <option value="" disabled selected>Select</option>
          {% for i in product.variation_set.sizes %}
          <option value="{{ i.variation_value | lower }}">{{ i.variation_value | capfirst }}</option>
          {% endfor %}
        </select>
      </div>
    </div>

        <hr>
        {% if product.stock < 0 %}
          <h5 class="text-danger">Out of Stock</h5>
        {% else %}          
              <button type="submit" class="btn btn-primary">
              <span class="text">Add to cart</span>
              <i class="fas fa-shopping-cart"></i>
              </button>
              <a href="{% url 'carts:cart' %}" type="submit" class="btn btn-outline-primary">
                <span class="text">View Cart</span>
                <i class="fas fa-eye"></i>
              </a>
        {% endif %}

    </article> <!-- product-info-aside .// -->
  </form>
            </main> <!-- col.// -->
        </div> <!-- row.// -->
    </div> <!-- card.// -->
    <!-- ============================ COMPONENT 1 END .// ================================= -->
    
    <br>
    
    <div class="row">
                <div class="col-md-9">
    
        

        <form action="{% url 'store:submit-review' product.id %}" method="POST">
          {% csrf_token %}
            <div>
              <label for="">
                How do you rate this product?
              </label>
              <br>
              <div class="rate" >
                <input type="radio" name="rating" id="rating10" value="5" required><label for="rating10" title="5"></label>
                <input type="radio" name="rating" id="rating9" value="4.5" required><label for="rating9" title="4..5" class="half"></label>
                <input type="radio" name="rating" id="rating8" value="4" required><label for="rating8" title="4"></label>
                <input type="radio" name="rating" id="rating7" value="3.5" required><label for="rating7" title="3.5" class="half"></label>
                <input type="radio" name="rating" id="rating6" value="3" required><label for="rating6" title="3"></label>
                <input type="radio" name="rating" id="rating5" value="2.5" required><label for="rating5" title="2.5" class="half"></label>
                <input type="radio" name="rating" id="rating4" value="2" required><label for="rating4" title="2"></label>
                <input type="radio" name="rating" id="rating3" value="1.5" required><label for="rating3" title="1.5" class="half"></label>
                <input type="radio" name="rating" id="rating2" value="1" required><label for="rating2" title="1"></label>
                <input type="radio" name="rating" id="rating1" value="0.5" required><label for="rating1" title="0.5" class="half"></label>
              </div>
<br>

              Review Title:
              <input type="text" class="form-control" name="subject">
              <br>
              Review:
              <textarea name="review"  rows="4" class="form-control"></textarea>
              <br>

              <!-- <input type="submit" value="Submit Review" class="btn btn-primary"> -->
              
              {% if user.is_authenticated %}
                {% if order_product %}
								  <input type="submit" value="Submit Review" class="btn btn-primary">
                  {% else %}
                  <p>You must have bought this product to make a review!</p>
                  {% endif %}
						  {% else %}
						    <p>You must be logged in to post a review. <span><a href="{% url 'accounts:login' %}">Login now</a></span></p>
						  {% endif %}
              
            </div>
            {% include 'includes/alerts.html' %}


        </form>   

        <br>
        <header class="section-heading">
          <h3>Customer Reviews </h3>
          <div class="rating-star">
            <span>
              <i class="fa fa-star{% if product.averageReview < 0.5 %}-o{% elif product.averageReview >= 0.5 and product.averageReview < 1 %}-half-o {% endif %}" aria-hidden="true"></i>
              <i class="fa fa-star{% if product.averageReview < 1.5 %}-o{% elif product.averageReview >= 1.5 and product.averageReview < 2 %}-half-o {% endif %}" aria-hidden="true"></i>
              <i class="fa fa-star{% if product.averageReview < 2.5 %}-o{% elif product.averageReview >= 2.5 and product.averageReview < 3 %}-half-o {% endif %}" aria-hidden="true"></i>
              <i class="fa fa-star{% if product.averageReview < 3.5 %}-o{% elif product.averageReview >= 3.5 and product.averageReview < 4 %}-half-o {% endif %}" aria-hidden="true"></i>
              <i class="fa fa-star{% if product.averageReview < 4.5 %}-o{% elif product.averageReview >= 4.5 and product.averageReview < 5 %}-half-o {% endif %}" aria-hidden="true"></i>
          <span>{{product.countReview}} reviews</span>
              </span>
          </div>
        
        </header>
        
        {% for review in reviews %}
                <article class="box mb-3">
                  <div class="icontext w-100">
        
                    <div class="text">
                      <span class="date text-muted float-md-right">{{review.updated_at}} </span>
                      <h6 class="mb-1">{{review.user.full_name}} </h6>
                      <div class="rating-star">
                        <span>
                          <i class="fa fa-star{% if review.rating == 0.5 %}-half-o{% elif review.rating < 1 %}-o {% endif %}" aria-hidden="true"></i>
                          <i class="fa fa-star{% if review.rating == 1.5 %}-half-o{% elif review.rating < 2 %}-o {% endif %}" aria-hidden="true"></i>
                          <i class="fa fa-star{% if review.rating == 2.5 %}-half-o{% elif review.rating < 3 %}-o {% endif %}" aria-hidden="true"></i>
                          <i class="fa fa-star{% if review.rating == 3.5 %}-half-o{% elif review.rating < 4 %}-o {% endif %}" aria-hidden="true"></i>
                          <i class="fa fa-star{% if review.rating == 4.5 %}-half-o{% elif review.rating < 5 %}-o {% endif %}" aria-hidden="true"></i>
                        </span>
                      </div>
                    </div>
                  </div> <!-- icontext.// -->
                  <div class="mt-3">
                    <h6>{{review.subject}}</h6>
                    <p>
                      {{review.review}}
                    </p>
                  </div>
                </article>
        {% endfor %}
        
    
        </div> <!-- col.// -->
    </div> <!-- row.// -->
    
    
    </div> <!-- container .//  -->
    </section>
    <!-- ========================= SECTION CONTENT END// ========================= -->
    

{% endblock %}